// ============================================
// HalalMap Georgia - Admin Controller
// Business logic for admin operations and authentication
// ============================================

import { Request, Response } from 'express';
import { pool } from '../config/database';
import { comparePassword, generateToken, hashPassword } from '../config/auth';

// ============================================
// ADMIN LOGIN
// Authenticates admin user and returns JWT token
// ============================================
export const adminLogin = async (req: Request, res: Response): Promise<void> => {
  try {
    const { username, password } = req.body;

    console.log(`🔐 Login attempt for user: ${username}`);

    // Find admin user by username
    const query = 'SELECT * FROM admin_users WHERE username = $1 AND active = true';
    const result = await pool.query(query, [username]);

    // Check if user exists
    if (result.rows.length === 0) {
      console.log(`❌ User not found: ${username}`);
      res.status(401).json({
        error: 'Authentication Failed',
        message: 'Invalid username or password',
      });
      return;
    }

    const adminUser = result.rows[0];

    // Verify password
    const isPasswordValid = await comparePassword(password, adminUser.password_hash);

    if (!isPasswordValid) {
      console.log(`❌ Invalid password for user: ${username}`);
      res.status(401).json({
        error: 'Authentication Failed',
        message: 'Invalid username or password',
      });
      return;
    }

    // Update last login timestamp
    await pool.query('UPDATE admin_users SET last_login = NOW() WHERE id = $1', [
      adminUser.id,
    ]);

    // Generate JWT token
    const token = generateToken({
      userId: adminUser.id,
      username: adminUser.username,
      email: adminUser.email,
    });

    console.log(`✅ Login successful for user: ${username}`);

    // Return token and user info
    res.json({
      success: true,
      message: 'Login successful',
      token,
      user: {
        id: adminUser.id,
        username: adminUser.username,
        email: adminUser.email,
        lastLogin: adminUser.last_login,
      },
    });
  } catch (error) {
    console.error('Login error:', error);
    res.status(500).json({
      error: 'Internal Server Error',
      message: 'Login failed',
    });
  }
};

// ============================================
// GET CURRENT USER INFO
// Returns info about currently authenticated admin
// ============================================
export const getCurrentUser = async (req: Request, res: Response): Promise<void> => {
  try {
    // req.user is set by authenticateToken middleware
    const userId = req.user?.userId;

    if (!userId) {
      res.status(401).json({
        error: 'Unauthorized',
        message: 'No user information found',
      });
      return;
    }

    // Fetch current user data
    const query = 'SELECT id, username, email, created_at, last_login FROM admin_users WHERE id = $1';
    const result = await pool.query(query, [userId]);

    if (result.rows.length === 0) {
      res.status(404).json({
        error: 'Not Found',
        message: 'User not found',
      });
      return;
    }

    res.json({
      success: true,
      data: result.rows[0],
    });
  } catch (error) {
    console.error('Error fetching current user:', error);
    res.status(500).json({
      error: 'Internal Server Error',
      message: 'Failed to fetch user information',
    });
  }
};

// ============================================
// CREATE PLACE (Admin Only)
// ============================================
export const createPlace = async (req: Request, res: Response): Promise<void> => {
  try {
    const {
      name,
      type,
      latitude,
      longitude,
      city,
      address,
      description,
      phone,
      website,
      verified,
    } = req.body;

    console.log(`➕ Creating new place: ${name} (${type})`);

    // Insert new place (location geography is auto-generated by trigger)
    const query = `
      INSERT INTO places (
        name, type, latitude, longitude, city, address, 
        description, phone, website, verified
      )
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
      RETURNING *
    `;

    const params = [
      name,
      type,
      latitude,
      longitude,
      city || null,
      address || null,
      description || null,
      phone || null,
      website || null,
      verified || false,
    ];

    const result = await pool.query(query, params);

    console.log(`✅ Place created with ID: ${result.rows[0].id}`);

    res.status(201).json({
      success: true,
      message: 'Place created successfully',
      data: result.rows[0],
    });
  } catch (error: any) {
    console.error('Error creating place:', error);

    // Handle unique constraint violations
    if (error.code === '23505') {
      res.status(409).json({
        error: 'Conflict',
        message: 'A place with this name already exists',
      });
      return;
    }

    res.status(500).json({
      error: 'Internal Server Error',
      message: 'Failed to create place',
    });
  }
};

// ============================================
// UPDATE PLACE (Admin Only)
// ============================================
export const updatePlace = async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params;
    const updates = req.body;

    console.log(`📝 Updating place ID: ${id}`);

    // Check if place exists
    const checkQuery = 'SELECT id FROM places WHERE id = $1';
    const checkResult = await pool.query(checkQuery, [id]);

    if (checkResult.rows.length === 0) {
      res.status(404).json({
        error: 'Not Found',
        message: `Place with ID ${id} not found`,
      });
      return;
    }

    // Build dynamic UPDATE query
    const fields = Object.keys(updates);
    if (fields.length === 0) {
      res.status(400).json({
        error: 'Bad Request',
        message: 'No fields to update',
      });
      return;
    }

    // Create SET clause dynamically
    const setClause = fields.map((field, index) => `${field} = $${index + 2}`).join(', ');
    const values = fields.map((field) => updates[field]);

    const updateQuery = `
      UPDATE places
      SET ${setClause}, updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `;

    const result = await pool.query(updateQuery, [id, ...values]);

    console.log(`✅ Place updated: ${result.rows[0].name}`);

    res.json({
      success: true,
      message: 'Place updated successfully',
      data: result.rows[0],
    });
  } catch (error) {
    console.error('Error updating place:', error);
    res.status(500).json({
      error: 'Internal Server Error',
      message: 'Failed to update place',
    });
  }
};

// ============================================
// DELETE PLACE (Admin Only)
// ============================================
export const deletePlace = async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params;

    console.log(`🗑️  Deleting place ID: ${id}`);

    // Delete place
    const query = 'DELETE FROM places WHERE id = $1 RETURNING id, name';
    const result = await pool.query(query, [id]);

    // Check if place was found
    if (result.rows.length === 0) {
      res.status(404).json({
        error: 'Not Found',
        message: `Place with ID ${id} not found`,
      });
      return;
    }

    console.log(`✅ Place deleted: ${result.rows[0].name}`);

    res.json({
      success: true,
      message: 'Place deleted successfully',
      data: {
        id: result.rows[0].id,
        name: result.rows[0].name,
      },
    });
  } catch (error) {
    console.error('Error deleting place:', error);
    res.status(500).json({
      error: 'Internal Server Error',
      message: 'Failed to delete place',
    });
  }
};

// ============================================
// TOGGLE VERIFIED STATUS (Admin Only)
// Quick endpoint to toggle verification
// ============================================
export const toggleVerified = async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params;

    console.log(`🔄 Toggling verified status for place ID: ${id}`);

    // Toggle verified status
    const query = `
      UPDATE places
      SET verified = NOT verified, updated_at = NOW()
      WHERE id = $1
      RETURNING id, name, verified
    `;

    const result = await pool.query(query, [id]);

    if (result.rows.length === 0) {
      res.status(404).json({
        error: 'Not Found',
        message: `Place with ID ${id} not found`,
      });
      return;
    }

    const place = result.rows[0];
    console.log(`✅ Place "${place.name}" verified status: ${place.verified}`);

    res.json({
      success: true,
      message: `Place ${place.verified ? 'verified' : 'unverified'} successfully`,
      data: place,
    });
  } catch (error) {
    console.error('Error toggling verified status:', error);
    res.status(500).json({
      error: 'Internal Server Error',
      message: 'Failed to toggle verified status',
    });
  }
};

// ============================================
// GET ADMIN DASHBOARD STATS
// Returns statistics for admin dashboard
// ============================================
export const getDashboardStats = async (req: Request, res: Response): Promise<void> => {
  try {
    // Get comprehensive stats
    const statsQuery = `
      SELECT 
        COUNT(*) as total_places,
        COUNT(CASE WHEN type = 'restaurant' THEN 1 END) as restaurants,
        COUNT(CASE WHEN type = 'mosque' THEN 1 END) as mosques,
        COUNT(CASE WHEN verified = true THEN 1 END) as verified,
        COUNT(CASE WHEN verified = false THEN 1 END) as unverified,
        COUNT(DISTINCT city) as cities
      FROM places
    `;

    const statsResult = await pool.query(statsQuery);
    const stats = statsResult.rows[0];

    // Get recent additions
    const recentQuery = `
      SELECT id, name, type, city, created_at
      FROM places
      ORDER BY created_at DESC
      LIMIT 5
    `;
    const recentResult = await pool.query(recentQuery);

    // Get places by city
    const cityQuery = `
      SELECT city, COUNT(*) as count
      FROM places
      WHERE city IS NOT NULL
      GROUP BY city
      ORDER BY count DESC
      LIMIT 5
    `;
    const cityResult = await pool.query(cityQuery);

    res.json({
      success: true,
      data: {
        overview: {
          total_places: parseInt(stats.total_places),
          restaurants: parseInt(stats.restaurants),
          mosques: parseInt(stats.mosques),
          verified: parseInt(stats.verified),
          unverified: parseInt(stats.unverified),
          cities: parseInt(stats.cities),
        },
        recent_additions: recentResult.rows,
        top_cities: cityResult.rows,
      },
    });
  } catch (error) {
    console.error('Error fetching dashboard stats:', error);
    res.status(500).json({
      error: 'Internal Server Error',
      message: 'Failed to fetch dashboard statistics',
    });
  }
};

// ============================================
// EXPORT CONTROLLER FUNCTIONS
// ============================================
export default {
  adminLogin,
  getCurrentUser,
  createPlace,
  updatePlace,
  deletePlace,
  toggleVerified,
  getDashboardStats,
};
